@echo off
echo Installing npm dependencies...
npm install
echo Installing Playwright browsers...
npx playwright install
echo Running Cucumber tests...
node node_modules\@cucumber\cucumber\bin\cucumber-js
echo Generating Allure report...
allure generate allure-results --clean -o allure-report
echo Opening Allure report...
allure open allure-report
pause
